// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module inference_linear_ap_fixed_16_6_5_3_0_ap_fixed_16_7_4_0_0_linear_config7_s (
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6
);


output   ap_ready;
input  [15:0] p_read;
input  [15:0] p_read1;
input  [15:0] p_read2;
input  [15:0] p_read3;
input  [15:0] p_read4;
input  [15:0] p_read5;
input  [15:0] p_read6;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;
output  [15:0] ap_return_6;

wire   [14:0] p_Val2_s_fu_104_p4;
wire   [0:0] tmp_fu_118_p3;
wire   [0:0] trunc_ln29_6_fu_100_p1;
wire   [0:0] and_ln374_fu_126_p2;
wire   [15:0] zext_ln377_fu_132_p1;
wire  signed [15:0] sext_ln818_fu_114_p1;
wire   [14:0] p_Val2_1_fu_142_p4;
wire   [0:0] tmp_3_fu_156_p3;
wire   [0:0] trunc_ln29_5_fu_96_p1;
wire   [0:0] and_ln374_1_fu_164_p2;
wire   [15:0] zext_ln377_1_fu_170_p1;
wire  signed [15:0] sext_ln818_1_fu_152_p1;
wire   [14:0] p_Val2_2_fu_180_p4;
wire   [0:0] tmp_4_fu_194_p3;
wire   [0:0] trunc_ln29_4_fu_92_p1;
wire   [0:0] and_ln374_2_fu_202_p2;
wire   [15:0] zext_ln377_2_fu_208_p1;
wire  signed [15:0] sext_ln818_2_fu_190_p1;
wire   [14:0] p_Val2_3_fu_218_p4;
wire   [0:0] tmp_5_fu_232_p3;
wire   [0:0] trunc_ln29_3_fu_88_p1;
wire   [0:0] and_ln374_3_fu_240_p2;
wire   [15:0] zext_ln377_3_fu_246_p1;
wire  signed [15:0] sext_ln818_3_fu_228_p1;
wire   [14:0] p_Val2_4_fu_256_p4;
wire   [0:0] tmp_6_fu_270_p3;
wire   [0:0] trunc_ln29_2_fu_84_p1;
wire   [0:0] and_ln374_4_fu_278_p2;
wire   [15:0] zext_ln377_4_fu_284_p1;
wire  signed [15:0] sext_ln818_4_fu_266_p1;
wire   [14:0] p_Val2_5_fu_294_p4;
wire   [0:0] tmp_7_fu_308_p3;
wire   [0:0] trunc_ln29_1_fu_80_p1;
wire   [0:0] and_ln374_5_fu_316_p2;
wire   [15:0] zext_ln377_5_fu_322_p1;
wire  signed [15:0] sext_ln818_5_fu_304_p1;
wire   [14:0] p_Val2_6_fu_332_p4;
wire   [0:0] tmp_8_fu_346_p3;
wire   [0:0] trunc_ln29_fu_76_p1;
wire   [0:0] and_ln374_6_fu_354_p2;
wire   [15:0] zext_ln377_6_fu_360_p1;
wire  signed [15:0] sext_ln818_6_fu_342_p1;
wire   [15:0] add_ln377_fu_136_p2;
wire   [15:0] add_ln377_1_fu_174_p2;
wire   [15:0] add_ln377_2_fu_212_p2;
wire   [15:0] add_ln377_3_fu_250_p2;
wire   [15:0] add_ln377_4_fu_288_p2;
wire   [15:0] add_ln377_5_fu_326_p2;
wire   [15:0] add_ln377_6_fu_364_p2;

assign add_ln377_1_fu_174_p2 = ($signed(zext_ln377_1_fu_170_p1) + $signed(sext_ln818_1_fu_152_p1));

assign add_ln377_2_fu_212_p2 = ($signed(zext_ln377_2_fu_208_p1) + $signed(sext_ln818_2_fu_190_p1));

assign add_ln377_3_fu_250_p2 = ($signed(zext_ln377_3_fu_246_p1) + $signed(sext_ln818_3_fu_228_p1));

assign add_ln377_4_fu_288_p2 = ($signed(zext_ln377_4_fu_284_p1) + $signed(sext_ln818_4_fu_266_p1));

assign add_ln377_5_fu_326_p2 = ($signed(zext_ln377_5_fu_322_p1) + $signed(sext_ln818_5_fu_304_p1));

assign add_ln377_6_fu_364_p2 = ($signed(zext_ln377_6_fu_360_p1) + $signed(sext_ln818_6_fu_342_p1));

assign add_ln377_fu_136_p2 = ($signed(zext_ln377_fu_132_p1) + $signed(sext_ln818_fu_114_p1));

assign and_ln374_1_fu_164_p2 = (trunc_ln29_5_fu_96_p1 & tmp_3_fu_156_p3);

assign and_ln374_2_fu_202_p2 = (trunc_ln29_4_fu_92_p1 & tmp_4_fu_194_p3);

assign and_ln374_3_fu_240_p2 = (trunc_ln29_3_fu_88_p1 & tmp_5_fu_232_p3);

assign and_ln374_4_fu_278_p2 = (trunc_ln29_2_fu_84_p1 & tmp_6_fu_270_p3);

assign and_ln374_5_fu_316_p2 = (trunc_ln29_1_fu_80_p1 & tmp_7_fu_308_p3);

assign and_ln374_6_fu_354_p2 = (trunc_ln29_fu_76_p1 & tmp_8_fu_346_p3);

assign and_ln374_fu_126_p2 = (trunc_ln29_6_fu_100_p1 & tmp_fu_118_p3);

assign ap_ready = 1'b1;

assign p_Val2_1_fu_142_p4 = {{p_read1[15:1]}};

assign p_Val2_2_fu_180_p4 = {{p_read2[15:1]}};

assign p_Val2_3_fu_218_p4 = {{p_read3[15:1]}};

assign p_Val2_4_fu_256_p4 = {{p_read4[15:1]}};

assign p_Val2_5_fu_294_p4 = {{p_read5[15:1]}};

assign p_Val2_6_fu_332_p4 = {{p_read6[15:1]}};

assign p_Val2_s_fu_104_p4 = {{p_read[15:1]}};

assign sext_ln818_1_fu_152_p1 = $signed(p_Val2_1_fu_142_p4);

assign sext_ln818_2_fu_190_p1 = $signed(p_Val2_2_fu_180_p4);

assign sext_ln818_3_fu_228_p1 = $signed(p_Val2_3_fu_218_p4);

assign sext_ln818_4_fu_266_p1 = $signed(p_Val2_4_fu_256_p4);

assign sext_ln818_5_fu_304_p1 = $signed(p_Val2_5_fu_294_p4);

assign sext_ln818_6_fu_342_p1 = $signed(p_Val2_6_fu_332_p4);

assign sext_ln818_fu_114_p1 = $signed(p_Val2_s_fu_104_p4);

assign tmp_3_fu_156_p3 = p_read1[32'd1];

assign tmp_4_fu_194_p3 = p_read2[32'd1];

assign tmp_5_fu_232_p3 = p_read3[32'd1];

assign tmp_6_fu_270_p3 = p_read4[32'd1];

assign tmp_7_fu_308_p3 = p_read5[32'd1];

assign tmp_8_fu_346_p3 = p_read6[32'd1];

assign tmp_fu_118_p3 = p_read[32'd1];

assign trunc_ln29_1_fu_80_p1 = p_read5[0:0];

assign trunc_ln29_2_fu_84_p1 = p_read4[0:0];

assign trunc_ln29_3_fu_88_p1 = p_read3[0:0];

assign trunc_ln29_4_fu_92_p1 = p_read2[0:0];

assign trunc_ln29_5_fu_96_p1 = p_read1[0:0];

assign trunc_ln29_6_fu_100_p1 = p_read[0:0];

assign trunc_ln29_fu_76_p1 = p_read6[0:0];

assign zext_ln377_1_fu_170_p1 = and_ln374_1_fu_164_p2;

assign zext_ln377_2_fu_208_p1 = and_ln374_2_fu_202_p2;

assign zext_ln377_3_fu_246_p1 = and_ln374_3_fu_240_p2;

assign zext_ln377_4_fu_284_p1 = and_ln374_4_fu_278_p2;

assign zext_ln377_5_fu_322_p1 = and_ln374_5_fu_316_p2;

assign zext_ln377_6_fu_360_p1 = and_ln374_6_fu_354_p2;

assign zext_ln377_fu_132_p1 = and_ln374_fu_126_p2;

assign ap_return_0 = add_ln377_fu_136_p2;

assign ap_return_1 = add_ln377_1_fu_174_p2;

assign ap_return_2 = add_ln377_2_fu_212_p2;

assign ap_return_3 = add_ln377_3_fu_250_p2;

assign ap_return_4 = add_ln377_4_fu_288_p2;

assign ap_return_5 = add_ln377_5_fu_326_p2;

assign ap_return_6 = add_ln377_6_fu_364_p2;

endmodule //inference_linear_ap_fixed_16_6_5_3_0_ap_fixed_16_7_4_0_0_linear_config7_s
