// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module inference_dense_latency_ap_fixed_16_7_4_0_0_ap_fixed_16_6_5_3_0_config5_s (
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6
);


output   ap_ready;
input  [15:0] p_read;
input  [15:0] p_read1;
input  [15:0] p_read2;
input  [15:0] p_read3;
input  [15:0] p_read4;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;
output  [15:0] ap_return_6;

wire  signed [15:0] mul_ln1270_fu_104_p0;
wire  signed [18:0] sext_ln1270_fu_597_p1;
wire  signed [4:0] mul_ln1270_fu_104_p1;
wire  signed [15:0] mul_ln1270_2_fu_108_p0;
wire  signed [18:0] sext_ln1273_23_fu_804_p1;
wire  signed [4:0] mul_ln1270_2_fu_108_p1;
wire   [4:0] mul_ln1270_3_fu_110_p1;
wire  signed [15:0] mul_ln1270_1_fu_116_p0;
wire   [4:0] mul_ln1270_1_fu_116_p1;
wire  signed [15:0] sext_ln1270_fu_597_p0;
wire  signed [15:0] trunc_ln1273_fu_602_p0;
wire   [14:0] trunc_ln1273_fu_602_p1;
wire  signed [15:0] shl_ln1273_s_fu_614_p1;
wire   [17:0] shl_ln1273_s_fu_614_p3;
wire  signed [18:0] sext_ln1273_19_fu_622_p1;
wire   [18:0] shl_ln_fu_606_p3;
wire  signed [15:0] shl_ln1273_14_fu_638_p1;
wire  signed [15:0] shl_ln1273_15_fu_646_p1;
wire   [16:0] shl_ln1273_15_fu_646_p3;
wire   [18:0] shl_ln1273_14_fu_638_p3;
wire  signed [18:0] sext_ln1273_20_fu_654_p1;
wire  signed [15:0] sext_ln1270_1_fu_676_p0;
wire  signed [15:0] shl_ln1273_16_fu_680_p1;
wire   [18:0] shl_ln1273_16_fu_680_p3;
wire  signed [15:0] shl_ln1273_17_fu_694_p1;
wire   [16:0] shl_ln1273_17_fu_694_p3;
wire  signed [18:0] sext_ln1273_21_fu_702_p1;
wire  signed [18:0] sext_ln1270_1_fu_676_p1;
wire  signed [15:0] sext_ln818_fu_724_p0;
wire  signed [15:0] tmp_fu_728_p1;
wire  signed [15:0] shl_ln1273_18_fu_736_p1;
wire   [17:0] shl_ln1273_18_fu_736_p3;
wire  signed [18:0] sext_ln1273_fu_744_p1;
wire  signed [18:0] sext_ln818_fu_724_p1;
wire  signed [15:0] shl_ln1273_19_fu_754_p1;
wire   [18:0] shl_ln1273_19_fu_754_p3;
wire   [18:0] sub_ln1273_fu_762_p2;
wire   [18:0] sub_ln1273_29_fu_774_p2;
wire  signed [15:0] shl_ln1273_20_fu_786_p1;
wire   [16:0] shl_ln1273_20_fu_786_p3;
wire  signed [18:0] sext_ln1273_22_fu_794_p1;
wire  signed [15:0] sext_ln1273_23_fu_804_p0;
wire  signed [15:0] shl_ln1273_21_fu_810_p1;
wire   [18:0] shl_ln1273_21_fu_810_p3;
wire  signed [15:0] shl_ln1273_22_fu_824_p1;
wire   [17:0] shl_ln1273_22_fu_824_p3;
wire  signed [18:0] sext_ln1273_24_fu_832_p1;
wire   [18:0] sub_ln1273_32_fu_836_p2;
wire  signed [15:0] shl_ln1273_23_fu_848_p1;
wire   [16:0] shl_ln1273_23_fu_848_p3;
wire  signed [18:0] sext_ln1273_25_fu_856_p1;
wire  signed [15:0] tmp_64_fu_877_p1;
wire  signed [15:0] shl_ln1273_24_fu_885_p1;
wire  signed [15:0] shl_ln1273_25_fu_893_p1;
wire   [16:0] shl_ln1273_25_fu_893_p3;
wire  signed [18:0] sext_ln1273_26_fu_901_p1;
wire   [18:0] shl_ln1273_24_fu_885_p3;
wire   [18:0] r_V_fu_626_p2;
wire   [18:0] mul_ln1270_1_fu_116_p2;
wire   [18:0] r_V_34_fu_632_p2;
wire   [18:0] r_V_40_fu_748_p2;
wire   [18:0] r_V_44_fu_818_p2;
wire   [18:0] r_V_36_fu_664_p2;
wire   [18:0] r_V_46_fu_860_p2;
wire   [18:0] r_V_37_fu_688_p2;
wire   [18:0] mul_ln1270_2_fu_108_p2;
wire   [18:0] mul_ln1270_fu_104_p2;
wire   [18:0] r_V_38_fu_706_p2;
wire   [18:0] r_V_41_fu_768_p2;
wire   [18:0] r_V_45_fu_842_p2;
wire   [18:0] mul_ln1270_3_fu_110_p2;
wire   [18:0] r_V_35_fu_658_p2;
wire   [18:0] sub_ln1270_2_fu_712_p2;
wire   [18:0] r_V_42_fu_780_p2;
wire   [18:0] sub_ln1270_fu_670_p2;
wire   [18:0] r_V_39_fu_718_p2;
wire   [18:0] r_V_43_fu_798_p2;
wire   [18:0] r_V_47_fu_866_p2;
wire   [18:0] r_V_48_fu_905_p2;
wire   [0:0] tmp_65_fu_911_p3;
wire   [0:0] tmp_66_fu_919_p3;
wire   [0:0] xor_ln838_37_fu_1087_p2;
wire   [0:0] tmp_fu_728_p3;
wire   [0:0] xor_ln838_fu_1093_p2;
wire   [0:0] tmp_72_fu_967_p3;
wire   [0:0] tmp_67_fu_927_p3;
wire   [0:0] tmp_73_fu_975_p3;
wire   [0:0] tmp_64_fu_877_p3;
wire   [0:0] xor_ln838_39_fu_1113_p2;
wire   [0:0] tmp_68_fu_935_p3;
wire   [0:0] xor_ln838_40_fu_1119_p2;
wire   [0:0] xor_ln838_38_fu_1107_p2;
wire   [0:0] xor_ln838_9_fu_1125_p2;
wire   [0:0] tmp_69_fu_943_p3;
wire   [0:0] xor_ln838_41_fu_1139_p2;
wire   [0:0] xor_ln838_10_fu_1145_p2;
wire   [0:0] tmp_75_fu_991_p3;
wire   [0:0] tmp_74_fu_983_p3;
wire   [0:0] tmp_77_fu_1007_p3;
wire   [0:0] tmp_78_fu_1015_p3;
wire   [0:0] xor_ln838_43_fu_1165_p2;
wire   [0:0] tmp_76_fu_999_p3;
wire   [0:0] xor_ln838_44_fu_1171_p2;
wire   [0:0] xor_ln838_42_fu_1159_p2;
wire   [0:0] xor_ln838_11_fu_1177_p2;
wire   [0:0] tmp_80_fu_1031_p3;
wire   [0:0] tmp_79_fu_1023_p3;
wire   [0:0] xor_ln838_46_fu_1197_p2;
wire   [0:0] tmp_81_fu_1039_p3;
wire   [0:0] xor_ln838_47_fu_1203_p2;
wire   [0:0] xor_ln838_45_fu_1191_p2;
wire   [0:0] xor_ln838_12_fu_1209_p2;
wire   [0:0] tmp_71_fu_959_p3;
wire   [0:0] tmp_70_fu_951_p3;
wire   [0:0] xor_ln838_13_fu_1223_p2;
wire   [0:0] tmp_83_fu_1055_p3;
wire   [0:0] tmp_82_fu_1047_p3;
wire   [0:0] tmp_85_fu_1071_p3;
wire   [0:0] tmp_86_fu_1079_p3;
wire   [0:0] xor_ln838_49_fu_1243_p2;
wire   [0:0] tmp_84_fu_1063_p3;
wire   [0:0] xor_ln838_50_fu_1249_p2;
wire   [0:0] xor_ln838_48_fu_1237_p2;
wire   [0:0] xor_ln838_14_fu_1255_p2;
wire   [15:0] shl_ln2_fu_1099_p3;
wire   [15:0] shl_ln838_9_fu_1131_p3;
wire   [15:0] shl_ln838_s_fu_1151_p3;
wire   [15:0] shl_ln838_1_fu_1183_p3;
wire   [15:0] shl_ln838_2_fu_1215_p3;
wire   [15:0] shl_ln838_3_fu_1229_p3;
wire   [15:0] shl_ln838_4_fu_1261_p3;

inference_mul_16s_5s_19_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 19 ))
mul_16s_5s_19_1_1_U1545(
    .din0(mul_ln1270_fu_104_p0),
    .din1(mul_ln1270_fu_104_p1),
    .dout(mul_ln1270_fu_104_p2)
);

inference_mul_16s_5s_19_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 19 ))
mul_16s_5s_19_1_1_U1546(
    .din0(mul_ln1270_2_fu_108_p0),
    .din1(mul_ln1270_2_fu_108_p1),
    .dout(mul_ln1270_2_fu_108_p2)
);

inference_mul_16s_5ns_19_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 19 ))
mul_16s_5ns_19_1_1_U1547(
    .din0(p_read4),
    .din1(mul_ln1270_3_fu_110_p1),
    .dout(mul_ln1270_3_fu_110_p2)
);

inference_mul_16s_5ns_19_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 19 ))
mul_16s_5ns_19_1_1_U1548(
    .din0(mul_ln1270_1_fu_116_p0),
    .din1(mul_ln1270_1_fu_116_p1),
    .dout(mul_ln1270_1_fu_116_p2)
);

assign ap_ready = 1'b1;

assign r_V_34_fu_632_p2 = ($signed(sext_ln1273_19_fu_622_p1) + $signed(sext_ln1270_fu_597_p1));

assign r_V_35_fu_658_p2 = ($signed(shl_ln1273_14_fu_638_p3) + $signed(sext_ln1273_20_fu_654_p1));

assign r_V_36_fu_664_p2 = ($signed(shl_ln1273_14_fu_638_p3) + $signed(sext_ln1270_fu_597_p1));

assign r_V_37_fu_688_p2 = (19'd0 - shl_ln1273_16_fu_680_p3);

assign r_V_38_fu_706_p2 = ($signed(shl_ln1273_16_fu_680_p3) + $signed(sext_ln1273_21_fu_702_p1));

assign r_V_39_fu_718_p2 = ($signed(shl_ln1273_16_fu_680_p3) - $signed(sext_ln1273_21_fu_702_p1));

assign r_V_40_fu_748_p2 = ($signed(sext_ln1273_fu_744_p1) + $signed(sext_ln818_fu_724_p1));

assign r_V_41_fu_768_p2 = ($signed(sub_ln1273_fu_762_p2) - $signed(sext_ln818_fu_724_p1));

assign r_V_42_fu_780_p2 = ($signed(sub_ln1273_29_fu_774_p2) - $signed(sext_ln818_fu_724_p1));

assign r_V_43_fu_798_p2 = ($signed(shl_ln1273_19_fu_754_p3) + $signed(sext_ln1273_22_fu_794_p1));

assign r_V_44_fu_818_p2 = ($signed(shl_ln1273_21_fu_810_p3) - $signed(sext_ln1273_23_fu_804_p1));

assign r_V_45_fu_842_p2 = ($signed(sub_ln1273_32_fu_836_p2) - $signed(sext_ln1273_23_fu_804_p1));

assign r_V_46_fu_860_p2 = ($signed(sext_ln1273_25_fu_856_p1) - $signed(shl_ln1273_21_fu_810_p3));

assign r_V_47_fu_866_p2 = (19'd0 - shl_ln1273_21_fu_810_p3);

assign r_V_48_fu_905_p2 = ($signed(sext_ln1273_26_fu_901_p1) - $signed(shl_ln1273_24_fu_885_p3));

assign r_V_fu_626_p2 = ($signed(sext_ln1273_19_fu_622_p1) - $signed(shl_ln_fu_606_p3));

assign sext_ln1270_1_fu_676_p1 = sext_ln1270_1_fu_676_p0;

assign sext_ln1270_fu_597_p1 = sext_ln1270_fu_597_p0;

assign sext_ln1273_19_fu_622_p1 = $signed(shl_ln1273_s_fu_614_p3);

assign sext_ln1273_20_fu_654_p1 = $signed(shl_ln1273_15_fu_646_p3);

assign sext_ln1273_21_fu_702_p1 = $signed(shl_ln1273_17_fu_694_p3);

assign sext_ln1273_22_fu_794_p1 = $signed(shl_ln1273_20_fu_786_p3);

assign sext_ln1273_23_fu_804_p1 = sext_ln1273_23_fu_804_p0;

assign sext_ln1273_24_fu_832_p1 = $signed(shl_ln1273_22_fu_824_p3);

assign sext_ln1273_25_fu_856_p1 = $signed(shl_ln1273_23_fu_848_p3);

assign sext_ln1273_26_fu_901_p1 = $signed(shl_ln1273_25_fu_893_p3);

assign sext_ln1273_fu_744_p1 = $signed(shl_ln1273_18_fu_736_p3);

assign sext_ln818_fu_724_p1 = sext_ln818_fu_724_p0;

assign shl_ln1273_14_fu_638_p3 = {{shl_ln1273_14_fu_638_p1}, {3'd0}};

assign shl_ln1273_15_fu_646_p3 = {{shl_ln1273_15_fu_646_p1}, {1'd0}};

assign shl_ln1273_16_fu_680_p3 = {{shl_ln1273_16_fu_680_p1}, {3'd0}};

assign shl_ln1273_17_fu_694_p3 = {{shl_ln1273_17_fu_694_p1}, {1'd0}};

assign shl_ln1273_18_fu_736_p3 = {{shl_ln1273_18_fu_736_p1}, {2'd0}};

assign shl_ln1273_19_fu_754_p3 = {{shl_ln1273_19_fu_754_p1}, {3'd0}};

assign shl_ln1273_20_fu_786_p3 = {{shl_ln1273_20_fu_786_p1}, {1'd0}};

assign shl_ln1273_21_fu_810_p3 = {{shl_ln1273_21_fu_810_p1}, {3'd0}};

assign shl_ln1273_22_fu_824_p3 = {{shl_ln1273_22_fu_824_p1}, {2'd0}};

assign shl_ln1273_23_fu_848_p3 = {{shl_ln1273_23_fu_848_p1}, {1'd0}};

assign shl_ln1273_24_fu_885_p3 = {{shl_ln1273_24_fu_885_p1}, {3'd0}};

assign shl_ln1273_25_fu_893_p3 = {{shl_ln1273_25_fu_893_p1}, {1'd0}};

assign shl_ln1273_s_fu_614_p3 = {{shl_ln1273_s_fu_614_p1}, {2'd0}};

assign shl_ln2_fu_1099_p3 = {{xor_ln838_fu_1093_p2}, {15'd0}};

assign shl_ln838_1_fu_1183_p3 = {{xor_ln838_11_fu_1177_p2}, {15'd0}};

assign shl_ln838_2_fu_1215_p3 = {{xor_ln838_12_fu_1209_p2}, {15'd0}};

assign shl_ln838_3_fu_1229_p3 = {{xor_ln838_13_fu_1223_p2}, {15'd0}};

assign shl_ln838_4_fu_1261_p3 = {{xor_ln838_14_fu_1255_p2}, {15'd0}};

assign shl_ln838_9_fu_1131_p3 = {{xor_ln838_9_fu_1125_p2}, {15'd0}};

assign shl_ln838_s_fu_1151_p3 = {{xor_ln838_10_fu_1145_p2}, {15'd0}};

assign shl_ln_fu_606_p3 = {{trunc_ln1273_fu_602_p1}, {4'd0}};

assign sub_ln1270_2_fu_712_p2 = ($signed(sext_ln1270_1_fu_676_p1) - $signed(shl_ln1273_16_fu_680_p3));

assign sub_ln1270_fu_670_p2 = ($signed(sext_ln1270_fu_597_p1) - $signed(shl_ln1273_14_fu_638_p3));

assign sub_ln1273_29_fu_774_p2 = ($signed(19'd0) - $signed(sext_ln1273_fu_744_p1));

assign sub_ln1273_32_fu_836_p2 = ($signed(19'd0) - $signed(sext_ln1273_24_fu_832_p1));

assign sub_ln1273_fu_762_p2 = (19'd0 - shl_ln1273_19_fu_754_p3);

assign tmp_64_fu_877_p3 = tmp_64_fu_877_p1[32'd15];

assign tmp_65_fu_911_p3 = r_V_fu_626_p2[32'd18];

assign tmp_66_fu_919_p3 = mul_ln1270_1_fu_116_p2[32'd18];

assign tmp_67_fu_927_p3 = r_V_34_fu_632_p2[32'd18];

assign tmp_68_fu_935_p3 = r_V_40_fu_748_p2[32'd18];

assign tmp_69_fu_943_p3 = r_V_44_fu_818_p2[32'd18];

assign tmp_70_fu_951_p3 = r_V_36_fu_664_p2[32'd18];

assign tmp_71_fu_959_p3 = r_V_46_fu_860_p2[32'd18];

assign tmp_72_fu_967_p3 = r_V_37_fu_688_p2[32'd18];

assign tmp_73_fu_975_p3 = mul_ln1270_2_fu_108_p2[32'd18];

assign tmp_74_fu_983_p3 = mul_ln1270_fu_104_p2[32'd18];

assign tmp_75_fu_991_p3 = r_V_38_fu_706_p2[32'd18];

assign tmp_76_fu_999_p3 = r_V_41_fu_768_p2[32'd18];

assign tmp_77_fu_1007_p3 = r_V_45_fu_842_p2[32'd18];

assign tmp_78_fu_1015_p3 = mul_ln1270_3_fu_110_p2[32'd18];

assign tmp_79_fu_1023_p3 = r_V_35_fu_658_p2[32'd18];

assign tmp_80_fu_1031_p3 = sub_ln1270_2_fu_712_p2[32'd18];

assign tmp_81_fu_1039_p3 = r_V_42_fu_780_p2[32'd18];

assign tmp_82_fu_1047_p3 = sub_ln1270_fu_670_p2[32'd18];

assign tmp_83_fu_1055_p3 = r_V_39_fu_718_p2[32'd18];

assign tmp_84_fu_1063_p3 = r_V_43_fu_798_p2[32'd18];

assign tmp_85_fu_1071_p3 = r_V_47_fu_866_p2[32'd18];

assign tmp_86_fu_1079_p3 = r_V_48_fu_905_p2[32'd18];

assign tmp_fu_728_p3 = tmp_fu_728_p1[32'd15];

assign trunc_ln1273_fu_602_p1 = trunc_ln1273_fu_602_p0[14:0];

assign xor_ln838_10_fu_1145_p2 = (xor_ln838_41_fu_1139_p2 ^ tmp_68_fu_935_p3);

assign xor_ln838_11_fu_1177_p2 = (xor_ln838_44_fu_1171_p2 ^ xor_ln838_42_fu_1159_p2);

assign xor_ln838_12_fu_1209_p2 = (xor_ln838_47_fu_1203_p2 ^ xor_ln838_45_fu_1191_p2);

assign xor_ln838_13_fu_1223_p2 = (tmp_71_fu_959_p3 ^ tmp_70_fu_951_p3);

assign xor_ln838_14_fu_1255_p2 = (xor_ln838_50_fu_1249_p2 ^ xor_ln838_48_fu_1237_p2);

assign xor_ln838_37_fu_1087_p2 = (tmp_66_fu_919_p3 ^ tmp_65_fu_911_p3);

assign xor_ln838_38_fu_1107_p2 = (tmp_72_fu_967_p3 ^ tmp_67_fu_927_p3);

assign xor_ln838_39_fu_1113_p2 = (tmp_73_fu_975_p3 ^ tmp_64_fu_877_p3);

assign xor_ln838_40_fu_1119_p2 = (xor_ln838_39_fu_1113_p2 ^ tmp_68_fu_935_p3);

assign xor_ln838_41_fu_1139_p2 = (tmp_69_fu_943_p3 ^ tmp_67_fu_927_p3);

assign xor_ln838_42_fu_1159_p2 = (tmp_75_fu_991_p3 ^ tmp_74_fu_983_p3);

assign xor_ln838_43_fu_1165_p2 = (tmp_78_fu_1015_p3 ^ tmp_77_fu_1007_p3);

assign xor_ln838_44_fu_1171_p2 = (xor_ln838_43_fu_1165_p2 ^ tmp_76_fu_999_p3);

assign xor_ln838_45_fu_1191_p2 = (tmp_80_fu_1031_p3 ^ tmp_79_fu_1023_p3);

assign xor_ln838_46_fu_1197_p2 = (tmp_66_fu_919_p3 ^ tmp_64_fu_877_p3);

assign xor_ln838_47_fu_1203_p2 = (xor_ln838_46_fu_1197_p2 ^ tmp_81_fu_1039_p3);

assign xor_ln838_48_fu_1237_p2 = (tmp_83_fu_1055_p3 ^ tmp_82_fu_1047_p3);

assign xor_ln838_49_fu_1243_p2 = (tmp_86_fu_1079_p3 ^ tmp_85_fu_1071_p3);

assign xor_ln838_50_fu_1249_p2 = (xor_ln838_49_fu_1243_p2 ^ tmp_84_fu_1063_p3);

assign xor_ln838_9_fu_1125_p2 = (xor_ln838_40_fu_1119_p2 ^ xor_ln838_38_fu_1107_p2);

assign xor_ln838_fu_1093_p2 = (xor_ln838_37_fu_1087_p2 ^ tmp_fu_728_p3);

assign ap_return_0 = shl_ln2_fu_1099_p3;

assign ap_return_1 = shl_ln838_9_fu_1131_p3;

assign ap_return_2 = shl_ln838_s_fu_1151_p3;

assign ap_return_3 = shl_ln838_1_fu_1183_p3;

assign ap_return_4 = shl_ln838_2_fu_1215_p3;

assign ap_return_5 = shl_ln838_3_fu_1229_p3;

assign ap_return_6 = shl_ln838_4_fu_1261_p3;

assign mul_ln1270_1_fu_116_p0 = sext_ln1273_23_fu_804_p1;

assign mul_ln1270_1_fu_116_p1 = 19'd11;

assign mul_ln1270_2_fu_108_p0 = sext_ln1273_23_fu_804_p1;

assign mul_ln1270_2_fu_108_p1 = 19'd524275;

assign mul_ln1270_3_fu_110_p1 = 19'd11;

assign mul_ln1270_fu_104_p0 = sext_ln1270_fu_597_p1;

assign mul_ln1270_fu_104_p1 = 19'd524275;

assign sext_ln1270_1_fu_676_p0 = p_read1;

assign sext_ln1270_fu_597_p0 = p_read;

assign sext_ln1273_23_fu_804_p0 = p_read3;

assign sext_ln818_fu_724_p0 = p_read2;

assign shl_ln1273_14_fu_638_p1 = p_read;

assign shl_ln1273_15_fu_646_p1 = p_read;

assign shl_ln1273_16_fu_680_p1 = p_read1;

assign shl_ln1273_17_fu_694_p1 = p_read1;

assign shl_ln1273_18_fu_736_p1 = p_read2;

assign shl_ln1273_19_fu_754_p1 = p_read2;

assign shl_ln1273_20_fu_786_p1 = p_read2;

assign shl_ln1273_21_fu_810_p1 = p_read3;

assign shl_ln1273_22_fu_824_p1 = p_read3;

assign shl_ln1273_23_fu_848_p1 = p_read3;

assign shl_ln1273_24_fu_885_p1 = p_read4;

assign shl_ln1273_25_fu_893_p1 = p_read4;

assign shl_ln1273_s_fu_614_p1 = p_read;

assign tmp_64_fu_877_p1 = p_read4;

assign tmp_fu_728_p1 = p_read2;

assign trunc_ln1273_fu_602_p0 = p_read;

endmodule //inference_dense_latency_ap_fixed_16_7_4_0_0_ap_fixed_16_6_5_3_0_config5_s
