// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module inference_dense_latency_ap_fixed_16_7_4_0_0_ap_fixed_16_6_5_3_0_config11_s (
        ap_ready,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        p_read8,
        ap_return
);


output   ap_ready;
input  [15:0] p_read1;
input  [15:0] p_read2;
input  [15:0] p_read3;
input  [15:0] p_read4;
input  [15:0] p_read5;
input  [15:0] p_read6;
input  [15:0] p_read7;
input  [15:0] p_read8;
output  [15:0] ap_return;

wire   [18:0] shl_ln_fu_106_p3;
wire  signed [15:0] sext_ln1270_fu_120_p0;
wire  signed [15:0] p_shl5_fu_124_p1;
wire  signed [18:0] sext_ln1270_fu_120_p1;
wire   [18:0] p_shl5_fu_124_p3;
wire  signed [15:0] sext_ln1273_fu_138_p0;
wire  signed [15:0] shl_ln1273_s_fu_142_p1;
wire   [18:0] shl_ln1273_s_fu_142_p3;
wire  signed [18:0] sext_ln1273_fu_138_p1;
wire  signed [15:0] sext_ln70_fu_156_p0;
wire  signed [15:0] tmp_fu_160_p1;
wire   [17:0] tmp_fu_160_p3;
wire  signed [18:0] sext_ln70_fu_156_p1;
wire  signed [18:0] sext_ln1273_27_fu_168_p1;
wire  signed [15:0] sext_ln1270_3_fu_178_p0;
wire  signed [15:0] p_shl1_fu_182_p1;
wire  signed [18:0] sext_ln1270_3_fu_178_p1;
wire   [18:0] p_shl1_fu_182_p3;
wire   [16:0] shl_ln1273_27_fu_204_p3;
wire  signed [18:0] sext_ln1273_28_fu_212_p1;
wire   [18:0] shl_ln1273_26_fu_196_p3;
wire  signed [15:0] sext_ln1273_29_fu_230_p0;
wire  signed [15:0] tmp_9_fu_234_p1;
wire   [17:0] tmp_9_fu_234_p3;
wire  signed [18:0] sext_ln1273_29_fu_230_p1;
wire  signed [18:0] sext_ln1273_30_fu_242_p1;
wire   [18:0] r_V_fu_114_p2;
wire   [18:0] sub_ln1270_fu_132_p2;
wire   [18:0] r_V_49_fu_150_p2;
wire   [18:0] r_V_50_fu_172_p2;
wire   [18:0] sub_ln1270_3_fu_190_p2;
wire   [18:0] r_V_51_fu_216_p2;
wire   [18:0] r_V_52_fu_246_p2;
wire   [0:0] tmp_89_fu_260_p3;
wire   [0:0] tmp_88_fu_252_p3;
wire   [0:0] tmp_90_fu_268_p3;
wire   [0:0] tmp_91_fu_276_p3;
wire   [0:0] xor_ln838_52_fu_314_p2;
wire   [0:0] xor_ln838_51_fu_308_p2;
wire   [0:0] tmp_92_fu_284_p3;
wire   [0:0] tmp_93_fu_292_p3;
wire   [0:0] tmp_87_fu_222_p3;
wire   [0:0] tmp_94_fu_300_p3;
wire   [0:0] xor_ln838_55_fu_332_p2;
wire   [0:0] xor_ln838_54_fu_326_p2;
wire   [0:0] xor_ln838_56_fu_338_p2;
wire   [0:0] xor_ln838_53_fu_320_p2;
wire   [0:0] xor_ln838_fu_344_p2;

assign ap_ready = 1'b1;

assign p_shl1_fu_182_p3 = {{p_shl1_fu_182_p1}, {3'd0}};

assign p_shl5_fu_124_p3 = {{p_shl5_fu_124_p1}, {3'd0}};

assign r_V_49_fu_150_p2 = ($signed(shl_ln1273_s_fu_142_p3) + $signed(sext_ln1273_fu_138_p1));

assign r_V_50_fu_172_p2 = ($signed(sext_ln70_fu_156_p1) - $signed(sext_ln1273_27_fu_168_p1));

assign r_V_51_fu_216_p2 = ($signed(sext_ln1273_28_fu_212_p1) - $signed(shl_ln1273_26_fu_196_p3));

assign r_V_52_fu_246_p2 = ($signed(sext_ln1273_29_fu_230_p1) - $signed(sext_ln1273_30_fu_242_p1));

assign r_V_fu_114_p2 = (19'd0 - shl_ln_fu_106_p3);

assign sext_ln1270_3_fu_178_p1 = sext_ln1270_3_fu_178_p0;

assign sext_ln1270_fu_120_p1 = sext_ln1270_fu_120_p0;

assign sext_ln1273_27_fu_168_p1 = $signed(tmp_fu_160_p3);

assign sext_ln1273_28_fu_212_p1 = $signed(shl_ln1273_27_fu_204_p3);

assign sext_ln1273_29_fu_230_p1 = sext_ln1273_29_fu_230_p0;

assign sext_ln1273_30_fu_242_p1 = $signed(tmp_9_fu_234_p3);

assign sext_ln1273_fu_138_p1 = sext_ln1273_fu_138_p0;

assign sext_ln70_fu_156_p1 = sext_ln70_fu_156_p0;

assign shl_ln1273_26_fu_196_p3 = {{p_read6}, {3'd0}};

assign shl_ln1273_27_fu_204_p3 = {{p_read6}, {1'd0}};

assign shl_ln1273_s_fu_142_p3 = {{shl_ln1273_s_fu_142_p1}, {3'd0}};

assign shl_ln_fu_106_p3 = {{p_read1}, {3'd0}};

assign sub_ln1270_3_fu_190_p2 = ($signed(sext_ln1270_3_fu_178_p1) - $signed(p_shl1_fu_182_p3));

assign sub_ln1270_fu_132_p2 = ($signed(sext_ln1270_fu_120_p1) - $signed(p_shl5_fu_124_p3));

assign tmp_87_fu_222_p3 = p_read7[32'd15];

assign tmp_88_fu_252_p3 = r_V_fu_114_p2[32'd18];

assign tmp_89_fu_260_p3 = sub_ln1270_fu_132_p2[32'd18];

assign tmp_90_fu_268_p3 = r_V_49_fu_150_p2[32'd18];

assign tmp_91_fu_276_p3 = r_V_50_fu_172_p2[32'd18];

assign tmp_92_fu_284_p3 = sub_ln1270_3_fu_190_p2[32'd18];

assign tmp_93_fu_292_p3 = r_V_51_fu_216_p2[32'd18];

assign tmp_94_fu_300_p3 = r_V_52_fu_246_p2[32'd18];

assign tmp_9_fu_234_p3 = {{tmp_9_fu_234_p1}, {2'd0}};

assign tmp_fu_160_p3 = {{tmp_fu_160_p1}, {2'd0}};

assign xor_ln838_51_fu_308_p2 = (tmp_89_fu_260_p3 ^ tmp_88_fu_252_p3);

assign xor_ln838_52_fu_314_p2 = (tmp_91_fu_276_p3 ^ tmp_90_fu_268_p3);

assign xor_ln838_53_fu_320_p2 = (xor_ln838_52_fu_314_p2 ^ xor_ln838_51_fu_308_p2);

assign xor_ln838_54_fu_326_p2 = (tmp_93_fu_292_p3 ^ tmp_92_fu_284_p3);

assign xor_ln838_55_fu_332_p2 = (tmp_94_fu_300_p3 ^ tmp_87_fu_222_p3);

assign xor_ln838_56_fu_338_p2 = (xor_ln838_55_fu_332_p2 ^ xor_ln838_54_fu_326_p2);

assign xor_ln838_fu_344_p2 = (xor_ln838_56_fu_338_p2 ^ xor_ln838_53_fu_320_p2);

assign ap_return = {{xor_ln838_fu_344_p2}, {15'd0}};

assign p_shl1_fu_182_p1 = p_read5;

assign p_shl5_fu_124_p1 = p_read2;

assign sext_ln1270_3_fu_178_p0 = p_read5;

assign sext_ln1270_fu_120_p0 = p_read2;

assign sext_ln1273_29_fu_230_p0 = p_read8;

assign sext_ln1273_fu_138_p0 = p_read3;

assign sext_ln70_fu_156_p0 = p_read4;

assign shl_ln1273_s_fu_142_p1 = p_read3;

assign tmp_9_fu_234_p1 = p_read8;

assign tmp_fu_160_p1 = p_read4;

endmodule //inference_dense_latency_ap_fixed_16_7_4_0_0_ap_fixed_16_6_5_3_0_config11_s
