// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module inference_dense_latency_ap_fixed_16_7_4_0_0_ap_fixed_16_6_5_3_0_config8_s (
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7
);


output   ap_ready;
input  [15:0] p_read;
input  [15:0] p_read1;
input  [15:0] p_read2;
input  [15:0] p_read3;
input  [15:0] p_read4;
input  [15:0] p_read5;
input  [15:0] p_read6;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;
output  [15:0] ap_return_6;
output  [15:0] ap_return_7;

wire  signed [15:0] sext_ln1273_fu_106_p0;
wire  signed [15:0] shl_ln_fu_110_p1;
wire  signed [15:0] shl_ln1273_1_fu_118_p1;
wire  signed [16:0] shl_ln1273_1_fu_118_p3;
wire   [18:0] shl_ln_fu_110_p3;
wire  signed [18:0] sext_ln1273_2_fu_130_p1;
wire  signed [15:0] shl_ln1273_2_fu_140_p1;
wire   [17:0] shl_ln1273_2_fu_140_p3;
wire  signed [18:0] sext_ln1273_3_fu_148_p1;
wire  signed [17:0] sext_ln1273_1_fu_126_p1;
wire   [17:0] r_V_2_fu_158_p2;
wire   [18:0] sub_ln1273_fu_172_p2;
wire  signed [18:0] sext_ln1273_fu_106_p1;
wire  signed [15:0] sext_ln1273_4_fu_208_p0;
wire  signed [15:0] p_shl7_fu_212_p1;
wire  signed [18:0] sext_ln1273_4_fu_208_p1;
wire   [18:0] p_shl7_fu_212_p3;
wire  signed [15:0] shl_ln1273_3_fu_226_p1;
wire   [17:0] shl_ln1273_3_fu_226_p3;
wire  signed [18:0] sext_ln1273_5_fu_234_p1;
wire  signed [15:0] tmp_25_fu_250_p1;
wire  signed [15:0] sext_ln818_fu_258_p0;
wire  signed [15:0] tmp_26_fu_262_p1;
wire  signed [15:0] shl_ln1273_4_fu_270_p1;
wire   [18:0] shl_ln1273_4_fu_270_p3;
wire  signed [15:0] tmp_6_fu_284_p1;
wire   [17:0] tmp_6_fu_284_p3;
wire  signed [18:0] sext_ln818_fu_258_p1;
wire  signed [18:0] sext_ln1273_10_fu_292_p1;
wire   [18:0] sub_ln1273_6_fu_278_p2;
wire  signed [15:0] sext_ln1273_6_fu_308_p0;
wire  signed [15:0] shl_ln1273_5_fu_312_p1;
wire   [18:0] shl_ln1273_5_fu_312_p3;
wire  signed [18:0] sext_ln1273_6_fu_308_p1;
wire  signed [15:0] shl_ln1273_6_fu_332_p1;
wire   [16:0] shl_ln1273_6_fu_332_p3;
wire  signed [18:0] sext_ln1273_7_fu_340_p1;
wire  signed [15:0] shl_ln1273_7_fu_350_p1;
wire   [17:0] shl_ln1273_7_fu_350_p3;
wire  signed [18:0] sext_ln1273_8_fu_358_p1;
wire   [18:0] sub_ln1273_12_fu_362_p2;
wire  signed [15:0] sext_ln1273_9_fu_380_p0;
wire  signed [15:0] shl_ln1273_8_fu_384_p1;
wire   [18:0] shl_ln1273_8_fu_384_p3;
wire   [18:0] r_V_17_fu_392_p2;
wire  signed [18:0] sext_ln1273_9_fu_380_p1;
wire  signed [15:0] tmp_7_fu_404_p1;
wire   [17:0] tmp_7_fu_404_p3;
wire  signed [18:0] sext_ln1273_13_fu_412_p1;
wire   [18:0] sub_ln1273_17_fu_422_p2;
wire  signed [15:0] shl_ln1273_s_fu_440_p1;
wire   [16:0] shl_ln1273_s_fu_440_p3;
wire  signed [18:0] sext_ln1273_11_fu_448_p1;
wire  signed [15:0] tmp_27_fu_458_p1;
wire  signed [15:0] sext_ln1273_12_fu_466_p0;
wire  signed [15:0] tmp_8_fu_470_p1;
wire   [17:0] tmp_8_fu_470_p3;
wire  signed [18:0] sext_ln1273_12_fu_466_p1;
wire  signed [18:0] sext_ln1273_15_fu_478_p1;
wire  signed [15:0] shl_ln1273_9_fu_494_p1;
wire  signed [15:0] shl_ln1273_10_fu_502_p1;
wire   [16:0] shl_ln1273_10_fu_502_p3;
wire   [18:0] shl_ln1273_9_fu_494_p3;
wire  signed [18:0] sext_ln1273_14_fu_510_p1;
wire  signed [15:0] sext_ln1270_fu_532_p0;
wire  signed [15:0] shl_ln1273_11_fu_536_p1;
wire   [17:0] shl_ln1273_11_fu_536_p3;
wire  signed [18:0] sext_ln1273_16_fu_544_p1;
wire  signed [18:0] sext_ln1270_fu_532_p1;
wire  signed [15:0] shl_ln1273_12_fu_560_p1;
wire  signed [16:0] shl_ln1273_12_fu_560_p3;
wire  signed [17:0] sext_ln1273_18_fu_572_p1;
wire   [17:0] r_V_30_fu_576_p2;
wire  signed [15:0] shl_ln1273_13_fu_590_p1;
wire   [18:0] shl_ln1273_13_fu_590_p3;
wire  signed [18:0] sext_ln1273_17_fu_568_p1;
wire   [18:0] sub_ln1273_26_fu_610_p2;
wire   [18:0] r_V_fu_134_p2;
wire   [18:0] sub_ln1270_fu_220_p2;
wire   [0:0] tmp_26_fu_262_p3;
wire   [0:0] tmp_29_fu_628_p3;
wire   [18:0] r_V_8_fu_238_p2;
wire   [18:0] r_V_23_fu_482_p2;
wire   [18:0] r_V_28_fu_554_p2;
wire   [18:0] r_V_1_fu_152_p2;
wire   [18:0] r_V_9_fu_244_p2;
wire   [18:0] r_V_12_fu_326_p2;
wire   [18:0] r_V_18_fu_398_p2;
wire   [18:0] r_V_29_fu_548_p2;
wire   [18:0] r_V_13_fu_344_p2;
wire   [18:0] r_V_19_fu_416_p2;
wire  signed [15:0] tmp_42_fu_738_p1;
wire   [18:0] r_V_24_fu_488_p2;
wire   [18:0] r_V_3_fu_178_p2;
wire   [18:0] r_V_14_fu_320_p2;
wire   [18:0] r_V_20_fu_428_p2;
wire   [18:0] r_V_4_fu_184_p2;
wire   [18:0] r_V_31_fu_598_p2;
wire   [18:0] r_V_5_fu_190_p2;
wire   [18:0] r_V_15_fu_368_p2;
wire   [18:0] r_V_21_fu_434_p2;
wire   [18:0] r_V_25_fu_514_p2;
wire   [18:0] r_V_32_fu_604_p2;
wire   [18:0] r_V_6_fu_196_p2;
wire   [18:0] r_V_10_fu_296_p2;
wire   [18:0] r_V_16_fu_374_p2;
wire   [18:0] r_V_22_fu_452_p2;
wire   [18:0] r_V_26_fu_520_p2;
wire   [18:0] r_V_33_fu_616_p2;
wire   [18:0] r_V_7_fu_202_p2;
wire   [18:0] r_V_11_fu_302_p2;
wire   [18:0] r_V_27_fu_526_p2;
wire   [18:0] sub_ln1270_1_fu_622_p2;
wire   [0:0] xor_ln813_fu_644_p2;
wire   [0:0] tmp_31_fu_650_p3;
wire   [0:0] tmp_33_fu_666_p3;
wire   [0:0] tmp_34_fu_674_p3;
wire   [0:0] xor_ln838_9_fu_920_p2;
wire   [0:0] tmp_32_fu_658_p3;
wire   [0:0] xor_ln838_10_fu_926_p2;
wire   [0:0] xor_ln838_fu_914_p2;
wire   [0:0] xor_ln838_1_fu_932_p2;
wire   [0:0] tmp_36_fu_690_p3;
wire   [0:0] tmp_35_fu_682_p3;
wire   [0:0] tmp_38_fu_706_p3;
wire   [0:0] tmp_39_fu_714_p3;
wire   [0:0] xor_ln838_12_fu_952_p2;
wire   [0:0] tmp_37_fu_698_p3;
wire   [0:0] xor_ln838_13_fu_958_p2;
wire   [0:0] xor_ln838_11_fu_946_p2;
wire   [0:0] xor_ln838_2_fu_964_p2;
wire   [0:0] tmp_40_fu_722_p3;
wire   [0:0] tmp_fu_164_p3;
wire   [0:0] tmp_42_fu_738_p3;
wire   [0:0] tmp_43_fu_746_p3;
wire   [0:0] xor_ln838_15_fu_984_p2;
wire   [0:0] tmp_41_fu_730_p3;
wire   [0:0] xor_ln838_16_fu_990_p2;
wire   [0:0] xor_ln838_14_fu_978_p2;
wire   [0:0] xor_ln838_3_fu_996_p2;
wire   [0:0] tmp_44_fu_754_p3;
wire   [0:0] tmp_25_fu_250_p3;
wire   [0:0] tmp_46_fu_770_p3;
wire   [0:0] tmp_28_fu_582_p3;
wire   [0:0] xor_ln838_18_fu_1016_p2;
wire   [0:0] tmp_45_fu_762_p3;
wire   [0:0] xor_ln838_19_fu_1022_p2;
wire   [0:0] xor_ln838_17_fu_1010_p2;
wire   [0:0] xor_ln838_4_fu_1028_p2;
wire   [0:0] tmp_30_fu_636_p3;
wire   [0:0] tmp_47_fu_778_p3;
wire   [0:0] tmp_48_fu_786_p3;
wire   [0:0] xor_ln838_21_fu_1048_p2;
wire   [0:0] xor_ln838_22_fu_1054_p2;
wire   [0:0] xor_ln838_20_fu_1042_p2;
wire   [0:0] xor_ln838_5_fu_1060_p2;
wire   [0:0] tmp_49_fu_794_p3;
wire   [0:0] xor_ln838_23_fu_1074_p2;
wire   [0:0] tmp_50_fu_802_p3;
wire   [0:0] tmp_51_fu_810_p3;
wire   [0:0] tmp_52_fu_818_p3;
wire   [0:0] tmp_53_fu_826_p3;
wire   [0:0] xor_ln838_26_fu_1092_p2;
wire   [0:0] xor_ln838_25_fu_1086_p2;
wire   [0:0] xor_ln838_27_fu_1098_p2;
wire   [0:0] xor_ln838_24_fu_1080_p2;
wire   [0:0] xor_ln838_6_fu_1104_p2;
wire   [0:0] tmp_54_fu_834_p3;
wire   [0:0] tmp_55_fu_842_p3;
wire   [0:0] xor_ln838_28_fu_1118_p2;
wire   [0:0] tmp_56_fu_850_p3;
wire   [0:0] tmp_57_fu_858_p3;
wire   [0:0] tmp_58_fu_866_p3;
wire   [0:0] tmp_59_fu_874_p3;
wire   [0:0] xor_ln838_31_fu_1136_p2;
wire   [0:0] xor_ln838_30_fu_1130_p2;
wire   [0:0] xor_ln838_32_fu_1142_p2;
wire   [0:0] xor_ln838_29_fu_1124_p2;
wire   [0:0] xor_ln838_7_fu_1148_p2;
wire   [0:0] tmp_61_fu_890_p3;
wire   [0:0] xor_ln838_33_fu_1162_p2;
wire   [0:0] tmp_60_fu_882_p3;
wire   [0:0] tmp_62_fu_898_p3;
wire   [0:0] tmp_63_fu_906_p3;
wire   [0:0] xor_ln838_35_fu_1174_p2;
wire   [0:0] tmp_27_fu_458_p3;
wire   [0:0] xor_ln838_36_fu_1180_p2;
wire   [0:0] xor_ln838_34_fu_1168_p2;
wire   [0:0] xor_ln838_8_fu_1186_p2;
wire   [15:0] shl_ln838_1_fu_938_p3;
wire   [15:0] shl_ln838_2_fu_970_p3;
wire   [15:0] shl_ln838_3_fu_1002_p3;
wire   [15:0] shl_ln838_4_fu_1034_p3;
wire   [15:0] shl_ln838_5_fu_1066_p3;
wire   [15:0] shl_ln838_6_fu_1110_p3;
wire   [15:0] shl_ln838_7_fu_1154_p3;
wire   [15:0] shl_ln838_8_fu_1192_p3;

assign ap_ready = 1'b1;

assign p_shl7_fu_212_p3 = {{p_shl7_fu_212_p1}, {3'd0}};

assign r_V_10_fu_296_p2 = ($signed(sext_ln818_fu_258_p1) - $signed(sext_ln1273_10_fu_292_p1));

assign r_V_11_fu_302_p2 = ($signed(sub_ln1273_6_fu_278_p2) - $signed(sext_ln818_fu_258_p1));

assign r_V_12_fu_326_p2 = ($signed(shl_ln1273_5_fu_312_p3) - $signed(sext_ln1273_6_fu_308_p1));

assign r_V_13_fu_344_p2 = ($signed(shl_ln1273_5_fu_312_p3) - $signed(sext_ln1273_7_fu_340_p1));

assign r_V_14_fu_320_p2 = (19'd0 - shl_ln1273_5_fu_312_p3);

assign r_V_15_fu_368_p2 = ($signed(sub_ln1273_12_fu_362_p2) - $signed(sext_ln1273_6_fu_308_p1));

assign r_V_16_fu_374_p2 = ($signed(sext_ln1273_8_fu_358_p1) - $signed(sext_ln1273_6_fu_308_p1));

assign r_V_17_fu_392_p2 = (19'd0 - shl_ln1273_8_fu_384_p3);

assign r_V_18_fu_398_p2 = ($signed(r_V_17_fu_392_p2) - $signed(sext_ln1273_9_fu_380_p1));

assign r_V_19_fu_416_p2 = ($signed(sext_ln1273_9_fu_380_p1) - $signed(sext_ln1273_13_fu_412_p1));

assign r_V_1_fu_152_p2 = ($signed(19'd0) - $signed(sext_ln1273_3_fu_148_p1));

assign r_V_20_fu_428_p2 = ($signed(sub_ln1273_17_fu_422_p2) - $signed(sext_ln1273_9_fu_380_p1));

assign r_V_21_fu_434_p2 = ($signed(shl_ln1273_8_fu_384_p3) + $signed(sext_ln1273_9_fu_380_p1));

assign r_V_22_fu_452_p2 = ($signed(r_V_17_fu_392_p2) - $signed(sext_ln1273_11_fu_448_p1));

assign r_V_23_fu_482_p2 = ($signed(sext_ln1273_12_fu_466_p1) - $signed(sext_ln1273_15_fu_478_p1));

assign r_V_24_fu_488_p2 = ($signed(sext_ln1273_15_fu_478_p1) + $signed(sext_ln1273_12_fu_466_p1));

assign r_V_25_fu_514_p2 = ($signed(shl_ln1273_9_fu_494_p3) + $signed(sext_ln1273_14_fu_510_p1));

assign r_V_26_fu_520_p2 = ($signed(shl_ln1273_9_fu_494_p3) + $signed(sext_ln1273_12_fu_466_p1));

assign r_V_27_fu_526_p2 = ($signed(sext_ln1273_14_fu_510_p1) - $signed(shl_ln1273_9_fu_494_p3));

assign r_V_28_fu_554_p2 = ($signed(sext_ln1273_16_fu_544_p1) - $signed(sext_ln1270_fu_532_p1));

assign r_V_29_fu_548_p2 = ($signed(19'd0) - $signed(sext_ln1273_16_fu_544_p1));

assign r_V_2_fu_158_p2 = ($signed(18'd0) - $signed(sext_ln1273_1_fu_126_p1));

assign r_V_30_fu_576_p2 = ($signed(18'd0) - $signed(sext_ln1273_18_fu_572_p1));

assign r_V_31_fu_598_p2 = ($signed(shl_ln1273_13_fu_590_p3) - $signed(sext_ln1273_17_fu_568_p1));

assign r_V_32_fu_604_p2 = ($signed(shl_ln1273_13_fu_590_p3) + $signed(sext_ln1270_fu_532_p1));

assign r_V_33_fu_616_p2 = ($signed(sub_ln1273_26_fu_610_p2) - $signed(sext_ln1273_17_fu_568_p1));

assign r_V_3_fu_178_p2 = ($signed(sub_ln1273_fu_172_p2) - $signed(sext_ln1273_2_fu_130_p1));

assign r_V_4_fu_184_p2 = ($signed(sext_ln1273_2_fu_130_p1) - $signed(shl_ln_fu_110_p3));

assign r_V_5_fu_190_p2 = ($signed(sext_ln1273_fu_106_p1) - $signed(sext_ln1273_3_fu_148_p1));

assign r_V_6_fu_196_p2 = ($signed(shl_ln_fu_110_p3) - $signed(sext_ln1273_fu_106_p1));

assign r_V_7_fu_202_p2 = ($signed(sext_ln1273_3_fu_148_p1) + $signed(sext_ln1273_fu_106_p1));

assign r_V_8_fu_238_p2 = ($signed(sext_ln1273_5_fu_234_p1) - $signed(sext_ln1273_4_fu_208_p1));

assign r_V_9_fu_244_p2 = ($signed(19'd0) - $signed(sext_ln1273_5_fu_234_p1));

assign r_V_fu_134_p2 = ($signed(shl_ln_fu_110_p3) - $signed(sext_ln1273_2_fu_130_p1));

assign sext_ln1270_fu_532_p1 = sext_ln1270_fu_532_p0;

assign sext_ln1273_10_fu_292_p1 = $signed(tmp_6_fu_284_p3);

assign sext_ln1273_11_fu_448_p1 = $signed(shl_ln1273_s_fu_440_p3);

assign sext_ln1273_12_fu_466_p1 = sext_ln1273_12_fu_466_p0;

assign sext_ln1273_13_fu_412_p1 = $signed(tmp_7_fu_404_p3);

assign sext_ln1273_14_fu_510_p1 = $signed(shl_ln1273_10_fu_502_p3);

assign sext_ln1273_15_fu_478_p1 = $signed(tmp_8_fu_470_p3);

assign sext_ln1273_16_fu_544_p1 = $signed(shl_ln1273_11_fu_536_p3);

assign sext_ln1273_17_fu_568_p1 = shl_ln1273_12_fu_560_p3;

assign sext_ln1273_18_fu_572_p1 = shl_ln1273_12_fu_560_p3;

assign sext_ln1273_1_fu_126_p1 = shl_ln1273_1_fu_118_p3;

assign sext_ln1273_2_fu_130_p1 = shl_ln1273_1_fu_118_p3;

assign sext_ln1273_3_fu_148_p1 = $signed(shl_ln1273_2_fu_140_p3);

assign sext_ln1273_4_fu_208_p1 = sext_ln1273_4_fu_208_p0;

assign sext_ln1273_5_fu_234_p1 = $signed(shl_ln1273_3_fu_226_p3);

assign sext_ln1273_6_fu_308_p1 = sext_ln1273_6_fu_308_p0;

assign sext_ln1273_7_fu_340_p1 = $signed(shl_ln1273_6_fu_332_p3);

assign sext_ln1273_8_fu_358_p1 = $signed(shl_ln1273_7_fu_350_p3);

assign sext_ln1273_9_fu_380_p1 = sext_ln1273_9_fu_380_p0;

assign sext_ln1273_fu_106_p1 = sext_ln1273_fu_106_p0;

assign sext_ln818_fu_258_p1 = sext_ln818_fu_258_p0;

assign shl_ln1273_10_fu_502_p3 = {{shl_ln1273_10_fu_502_p1}, {1'd0}};

assign shl_ln1273_11_fu_536_p3 = {{shl_ln1273_11_fu_536_p1}, {2'd0}};

assign shl_ln1273_12_fu_560_p3 = {{shl_ln1273_12_fu_560_p1}, {1'd0}};

assign shl_ln1273_13_fu_590_p3 = {{shl_ln1273_13_fu_590_p1}, {3'd0}};

assign shl_ln1273_1_fu_118_p3 = {{shl_ln1273_1_fu_118_p1}, {1'd0}};

assign shl_ln1273_2_fu_140_p3 = {{shl_ln1273_2_fu_140_p1}, {2'd0}};

assign shl_ln1273_3_fu_226_p3 = {{shl_ln1273_3_fu_226_p1}, {2'd0}};

assign shl_ln1273_4_fu_270_p3 = {{shl_ln1273_4_fu_270_p1}, {3'd0}};

assign shl_ln1273_5_fu_312_p3 = {{shl_ln1273_5_fu_312_p1}, {3'd0}};

assign shl_ln1273_6_fu_332_p3 = {{shl_ln1273_6_fu_332_p1}, {1'd0}};

assign shl_ln1273_7_fu_350_p3 = {{shl_ln1273_7_fu_350_p1}, {2'd0}};

assign shl_ln1273_8_fu_384_p3 = {{shl_ln1273_8_fu_384_p1}, {3'd0}};

assign shl_ln1273_9_fu_494_p3 = {{shl_ln1273_9_fu_494_p1}, {3'd0}};

assign shl_ln1273_s_fu_440_p3 = {{shl_ln1273_s_fu_440_p1}, {1'd0}};

assign shl_ln838_1_fu_938_p3 = {{xor_ln838_1_fu_932_p2}, {15'd0}};

assign shl_ln838_2_fu_970_p3 = {{xor_ln838_2_fu_964_p2}, {15'd0}};

assign shl_ln838_3_fu_1002_p3 = {{xor_ln838_3_fu_996_p2}, {15'd0}};

assign shl_ln838_4_fu_1034_p3 = {{xor_ln838_4_fu_1028_p2}, {15'd0}};

assign shl_ln838_5_fu_1066_p3 = {{xor_ln838_5_fu_1060_p2}, {15'd0}};

assign shl_ln838_6_fu_1110_p3 = {{xor_ln838_6_fu_1104_p2}, {15'd0}};

assign shl_ln838_7_fu_1154_p3 = {{xor_ln838_7_fu_1148_p2}, {15'd0}};

assign shl_ln838_8_fu_1192_p3 = {{xor_ln838_8_fu_1186_p2}, {15'd0}};

assign shl_ln_fu_110_p3 = {{shl_ln_fu_110_p1}, {3'd0}};

assign sub_ln1270_1_fu_622_p2 = ($signed(sext_ln1270_fu_532_p1) - $signed(shl_ln1273_13_fu_590_p3));

assign sub_ln1270_fu_220_p2 = ($signed(sext_ln1273_4_fu_208_p1) - $signed(p_shl7_fu_212_p3));

assign sub_ln1273_12_fu_362_p2 = ($signed(19'd0) - $signed(sext_ln1273_8_fu_358_p1));

assign sub_ln1273_17_fu_422_p2 = ($signed(19'd0) - $signed(sext_ln1273_13_fu_412_p1));

assign sub_ln1273_26_fu_610_p2 = (19'd0 - shl_ln1273_13_fu_590_p3);

assign sub_ln1273_6_fu_278_p2 = (19'd0 - shl_ln1273_4_fu_270_p3);

assign sub_ln1273_fu_172_p2 = (19'd0 - shl_ln_fu_110_p3);

assign tmp_25_fu_250_p3 = tmp_25_fu_250_p1[32'd15];

assign tmp_26_fu_262_p3 = tmp_26_fu_262_p1[32'd15];

assign tmp_27_fu_458_p3 = tmp_27_fu_458_p1[32'd15];

assign tmp_28_fu_582_p3 = r_V_30_fu_576_p2[32'd17];

assign tmp_29_fu_628_p3 = r_V_fu_134_p2[32'd18];

assign tmp_30_fu_636_p3 = sub_ln1270_fu_220_p2[32'd18];

assign tmp_31_fu_650_p3 = r_V_8_fu_238_p2[32'd18];

assign tmp_32_fu_658_p3 = r_V_17_fu_392_p2[32'd18];

assign tmp_33_fu_666_p3 = r_V_23_fu_482_p2[32'd18];

assign tmp_34_fu_674_p3 = r_V_28_fu_554_p2[32'd18];

assign tmp_35_fu_682_p3 = r_V_1_fu_152_p2[32'd18];

assign tmp_36_fu_690_p3 = r_V_9_fu_244_p2[32'd18];

assign tmp_37_fu_698_p3 = r_V_12_fu_326_p2[32'd18];

assign tmp_38_fu_706_p3 = r_V_18_fu_398_p2[32'd18];

assign tmp_39_fu_714_p3 = r_V_29_fu_548_p2[32'd18];

assign tmp_40_fu_722_p3 = r_V_13_fu_344_p2[32'd18];

assign tmp_41_fu_730_p3 = r_V_19_fu_416_p2[32'd18];

assign tmp_42_fu_738_p3 = tmp_42_fu_738_p1[32'd15];

assign tmp_43_fu_746_p3 = r_V_24_fu_488_p2[32'd18];

assign tmp_44_fu_754_p3 = r_V_3_fu_178_p2[32'd18];

assign tmp_45_fu_762_p3 = r_V_14_fu_320_p2[32'd18];

assign tmp_46_fu_770_p3 = r_V_20_fu_428_p2[32'd18];

assign tmp_47_fu_778_p3 = r_V_4_fu_184_p2[32'd18];

assign tmp_48_fu_786_p3 = r_V_31_fu_598_p2[32'd18];

assign tmp_49_fu_794_p3 = r_V_5_fu_190_p2[32'd18];

assign tmp_50_fu_802_p3 = r_V_15_fu_368_p2[32'd18];

assign tmp_51_fu_810_p3 = r_V_21_fu_434_p2[32'd18];

assign tmp_52_fu_818_p3 = r_V_25_fu_514_p2[32'd18];

assign tmp_53_fu_826_p3 = r_V_32_fu_604_p2[32'd18];

assign tmp_54_fu_834_p3 = r_V_6_fu_196_p2[32'd18];

assign tmp_55_fu_842_p3 = r_V_10_fu_296_p2[32'd18];

assign tmp_56_fu_850_p3 = r_V_16_fu_374_p2[32'd18];

assign tmp_57_fu_858_p3 = r_V_22_fu_452_p2[32'd18];

assign tmp_58_fu_866_p3 = r_V_26_fu_520_p2[32'd18];

assign tmp_59_fu_874_p3 = r_V_33_fu_616_p2[32'd18];

assign tmp_60_fu_882_p3 = r_V_7_fu_202_p2[32'd18];

assign tmp_61_fu_890_p3 = r_V_11_fu_302_p2[32'd18];

assign tmp_62_fu_898_p3 = r_V_27_fu_526_p2[32'd18];

assign tmp_63_fu_906_p3 = sub_ln1270_1_fu_622_p2[32'd18];

assign tmp_6_fu_284_p3 = {{tmp_6_fu_284_p1}, {2'd0}};

assign tmp_7_fu_404_p3 = {{tmp_7_fu_404_p1}, {2'd0}};

assign tmp_8_fu_470_p3 = {{tmp_8_fu_470_p1}, {2'd0}};

assign tmp_fu_164_p3 = r_V_2_fu_158_p2[32'd17];

assign xor_ln813_fu_644_p2 = (tmp_29_fu_628_p3 ^ tmp_26_fu_262_p3);

assign xor_ln838_10_fu_926_p2 = (xor_ln838_9_fu_920_p2 ^ tmp_32_fu_658_p3);

assign xor_ln838_11_fu_946_p2 = (tmp_36_fu_690_p3 ^ tmp_35_fu_682_p3);

assign xor_ln838_12_fu_952_p2 = (tmp_39_fu_714_p3 ^ tmp_38_fu_706_p3);

assign xor_ln838_13_fu_958_p2 = (xor_ln838_12_fu_952_p2 ^ tmp_37_fu_698_p3);

assign xor_ln838_14_fu_978_p2 = (tmp_fu_164_p3 ^ tmp_40_fu_722_p3);

assign xor_ln838_15_fu_984_p2 = (tmp_43_fu_746_p3 ^ tmp_42_fu_738_p3);

assign xor_ln838_16_fu_990_p2 = (xor_ln838_15_fu_984_p2 ^ tmp_41_fu_730_p3);

assign xor_ln838_17_fu_1010_p2 = (tmp_44_fu_754_p3 ^ tmp_25_fu_250_p3);

assign xor_ln838_18_fu_1016_p2 = (tmp_46_fu_770_p3 ^ tmp_28_fu_582_p3);

assign xor_ln838_19_fu_1022_p2 = (xor_ln838_18_fu_1016_p2 ^ tmp_45_fu_762_p3);

assign xor_ln838_1_fu_932_p2 = (xor_ln838_fu_914_p2 ^ xor_ln838_10_fu_926_p2);

assign xor_ln838_20_fu_1042_p2 = (tmp_47_fu_778_p3 ^ tmp_30_fu_636_p3);

assign xor_ln838_21_fu_1048_p2 = (tmp_48_fu_786_p3 ^ tmp_33_fu_666_p3);

assign xor_ln838_22_fu_1054_p2 = (xor_ln838_21_fu_1048_p2 ^ tmp_41_fu_730_p3);

assign xor_ln838_23_fu_1074_p2 = (tmp_49_fu_794_p3 ^ tmp_26_fu_262_p3);

assign xor_ln838_24_fu_1080_p2 = (xor_ln838_23_fu_1074_p2 ^ tmp_30_fu_636_p3);

assign xor_ln838_25_fu_1086_p2 = (tmp_51_fu_810_p3 ^ tmp_50_fu_802_p3);

assign xor_ln838_26_fu_1092_p2 = (tmp_53_fu_826_p3 ^ tmp_52_fu_818_p3);

assign xor_ln838_27_fu_1098_p2 = (xor_ln838_26_fu_1092_p2 ^ xor_ln838_25_fu_1086_p2);

assign xor_ln838_28_fu_1118_p2 = (tmp_55_fu_842_p3 ^ tmp_54_fu_834_p3);

assign xor_ln838_29_fu_1124_p2 = (xor_ln838_28_fu_1118_p2 ^ tmp_31_fu_650_p3);

assign xor_ln838_2_fu_964_p2 = (xor_ln838_13_fu_958_p2 ^ xor_ln838_11_fu_946_p2);

assign xor_ln838_30_fu_1130_p2 = (tmp_57_fu_858_p3 ^ tmp_56_fu_850_p3);

assign xor_ln838_31_fu_1136_p2 = (tmp_59_fu_874_p3 ^ tmp_58_fu_866_p3);

assign xor_ln838_32_fu_1142_p2 = (xor_ln838_31_fu_1136_p2 ^ xor_ln838_30_fu_1130_p2);

assign xor_ln838_33_fu_1162_p2 = (tmp_61_fu_890_p3 ^ tmp_25_fu_250_p3);

assign xor_ln838_34_fu_1168_p2 = (xor_ln838_33_fu_1162_p2 ^ tmp_60_fu_882_p3);

assign xor_ln838_35_fu_1174_p2 = (tmp_63_fu_906_p3 ^ tmp_62_fu_898_p3);

assign xor_ln838_36_fu_1180_p2 = (xor_ln838_35_fu_1174_p2 ^ tmp_27_fu_458_p3);

assign xor_ln838_3_fu_996_p2 = (xor_ln838_16_fu_990_p2 ^ xor_ln838_14_fu_978_p2);

assign xor_ln838_4_fu_1028_p2 = (xor_ln838_19_fu_1022_p2 ^ xor_ln838_17_fu_1010_p2);

assign xor_ln838_5_fu_1060_p2 = (xor_ln838_22_fu_1054_p2 ^ xor_ln838_20_fu_1042_p2);

assign xor_ln838_6_fu_1104_p2 = (xor_ln838_27_fu_1098_p2 ^ xor_ln838_24_fu_1080_p2);

assign xor_ln838_7_fu_1148_p2 = (xor_ln838_32_fu_1142_p2 ^ xor_ln838_29_fu_1124_p2);

assign xor_ln838_8_fu_1186_p2 = (xor_ln838_36_fu_1180_p2 ^ xor_ln838_34_fu_1168_p2);

assign xor_ln838_9_fu_920_p2 = (tmp_34_fu_674_p3 ^ tmp_33_fu_666_p3);

assign xor_ln838_fu_914_p2 = (xor_ln813_fu_644_p2 ^ tmp_31_fu_650_p3);

assign ap_return_0 = shl_ln838_1_fu_938_p3;

assign ap_return_1 = shl_ln838_2_fu_970_p3;

assign ap_return_2 = shl_ln838_3_fu_1002_p3;

assign ap_return_3 = shl_ln838_4_fu_1034_p3;

assign ap_return_4 = shl_ln838_5_fu_1066_p3;

assign ap_return_5 = shl_ln838_6_fu_1110_p3;

assign ap_return_6 = shl_ln838_7_fu_1154_p3;

assign ap_return_7 = shl_ln838_8_fu_1192_p3;

assign p_shl7_fu_212_p1 = p_read1;

assign sext_ln1270_fu_532_p0 = p_read6;

assign sext_ln1273_12_fu_466_p0 = p_read5;

assign sext_ln1273_4_fu_208_p0 = p_read1;

assign sext_ln1273_6_fu_308_p0 = p_read3;

assign sext_ln1273_9_fu_380_p0 = p_read4;

assign sext_ln1273_fu_106_p0 = p_read;

assign sext_ln818_fu_258_p0 = p_read2;

assign shl_ln1273_10_fu_502_p1 = p_read5;

assign shl_ln1273_11_fu_536_p1 = p_read6;

assign shl_ln1273_12_fu_560_p1 = p_read6;

assign shl_ln1273_13_fu_590_p1 = p_read6;

assign shl_ln1273_1_fu_118_p1 = p_read;

assign shl_ln1273_2_fu_140_p1 = p_read;

assign shl_ln1273_3_fu_226_p1 = p_read1;

assign shl_ln1273_4_fu_270_p1 = p_read2;

assign shl_ln1273_5_fu_312_p1 = p_read3;

assign shl_ln1273_6_fu_332_p1 = p_read3;

assign shl_ln1273_7_fu_350_p1 = p_read3;

assign shl_ln1273_8_fu_384_p1 = p_read4;

assign shl_ln1273_9_fu_494_p1 = p_read5;

assign shl_ln1273_s_fu_440_p1 = p_read4;

assign shl_ln_fu_110_p1 = p_read;

assign tmp_25_fu_250_p1 = p_read1;

assign tmp_26_fu_262_p1 = p_read2;

assign tmp_27_fu_458_p1 = p_read4;

assign tmp_42_fu_738_p1 = p_read6;

assign tmp_6_fu_284_p1 = p_read2;

assign tmp_7_fu_404_p1 = p_read4;

assign tmp_8_fu_470_p1 = p_read5;

endmodule //inference_dense_latency_ap_fixed_16_7_4_0_0_ap_fixed_16_6_5_3_0_config8_s
