// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module inference_linear_ap_fixed_16_6_5_3_0_ap_fixed_16_7_4_0_0_linear_config10_s (
        ap_ready,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read8,
        p_read9,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7
);


output   ap_ready;
input  [15:0] p_read1;
input  [15:0] p_read2;
input  [15:0] p_read3;
input  [15:0] p_read4;
input  [15:0] p_read5;
input  [15:0] p_read6;
input  [15:0] p_read8;
input  [15:0] p_read9;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;
output  [15:0] ap_return_6;
output  [15:0] ap_return_7;

wire   [14:0] p_Val2_s_fu_116_p4;
wire   [0:0] tmp_fu_130_p3;
wire   [0:0] trunc_ln29_17_fu_112_p1;
wire   [0:0] and_ln374_fu_138_p2;
wire   [15:0] zext_ln377_fu_144_p1;
wire  signed [15:0] sext_ln818_fu_126_p1;
wire   [14:0] p_Val2_11_fu_154_p4;
wire   [0:0] tmp_13_fu_168_p3;
wire   [0:0] trunc_ln29_16_fu_108_p1;
wire   [0:0] and_ln374_11_fu_176_p2;
wire   [15:0] zext_ln377_11_fu_182_p1;
wire  signed [15:0] sext_ln818_11_fu_164_p1;
wire   [14:0] p_Val2_12_fu_192_p4;
wire   [0:0] tmp_14_fu_206_p3;
wire   [0:0] trunc_ln29_15_fu_104_p1;
wire   [0:0] and_ln374_12_fu_214_p2;
wire   [15:0] zext_ln377_12_fu_220_p1;
wire  signed [15:0] sext_ln818_12_fu_202_p1;
wire   [14:0] p_Val2_13_fu_230_p4;
wire   [0:0] tmp_15_fu_244_p3;
wire   [0:0] trunc_ln29_14_fu_100_p1;
wire   [0:0] and_ln374_13_fu_252_p2;
wire   [15:0] zext_ln377_13_fu_258_p1;
wire  signed [15:0] sext_ln818_13_fu_240_p1;
wire   [14:0] p_Val2_14_fu_268_p4;
wire   [0:0] tmp_16_fu_282_p3;
wire   [0:0] trunc_ln29_13_fu_96_p1;
wire   [0:0] and_ln374_14_fu_290_p2;
wire   [15:0] zext_ln377_14_fu_296_p1;
wire  signed [15:0] sext_ln818_14_fu_278_p1;
wire   [14:0] p_Val2_15_fu_306_p4;
wire   [0:0] tmp_17_fu_320_p3;
wire   [0:0] trunc_ln29_12_fu_92_p1;
wire   [0:0] and_ln374_15_fu_328_p2;
wire   [15:0] zext_ln377_15_fu_334_p1;
wire  signed [15:0] sext_ln818_15_fu_316_p1;
wire   [14:0] p_Val2_16_fu_344_p4;
wire   [0:0] tmp_18_fu_358_p3;
wire   [0:0] trunc_ln29_11_fu_88_p1;
wire   [0:0] and_ln374_16_fu_366_p2;
wire   [15:0] zext_ln377_16_fu_372_p1;
wire  signed [15:0] sext_ln818_16_fu_354_p1;
wire   [14:0] p_Val2_17_fu_382_p4;
wire   [0:0] tmp_19_fu_396_p3;
wire   [0:0] trunc_ln29_fu_84_p1;
wire   [0:0] and_ln374_17_fu_404_p2;
wire   [15:0] zext_ln377_17_fu_410_p1;
wire  signed [15:0] sext_ln818_17_fu_392_p1;
wire   [15:0] add_ln377_fu_148_p2;
wire   [15:0] add_ln377_11_fu_186_p2;
wire   [15:0] add_ln377_12_fu_224_p2;
wire   [15:0] add_ln377_13_fu_262_p2;
wire   [15:0] add_ln377_14_fu_300_p2;
wire   [15:0] add_ln377_15_fu_338_p2;
wire   [15:0] add_ln377_16_fu_376_p2;
wire   [15:0] add_ln377_17_fu_414_p2;

assign add_ln377_11_fu_186_p2 = ($signed(zext_ln377_11_fu_182_p1) + $signed(sext_ln818_11_fu_164_p1));

assign add_ln377_12_fu_224_p2 = ($signed(zext_ln377_12_fu_220_p1) + $signed(sext_ln818_12_fu_202_p1));

assign add_ln377_13_fu_262_p2 = ($signed(zext_ln377_13_fu_258_p1) + $signed(sext_ln818_13_fu_240_p1));

assign add_ln377_14_fu_300_p2 = ($signed(zext_ln377_14_fu_296_p1) + $signed(sext_ln818_14_fu_278_p1));

assign add_ln377_15_fu_338_p2 = ($signed(zext_ln377_15_fu_334_p1) + $signed(sext_ln818_15_fu_316_p1));

assign add_ln377_16_fu_376_p2 = ($signed(zext_ln377_16_fu_372_p1) + $signed(sext_ln818_16_fu_354_p1));

assign add_ln377_17_fu_414_p2 = ($signed(zext_ln377_17_fu_410_p1) + $signed(sext_ln818_17_fu_392_p1));

assign add_ln377_fu_148_p2 = ($signed(zext_ln377_fu_144_p1) + $signed(sext_ln818_fu_126_p1));

assign and_ln374_11_fu_176_p2 = (trunc_ln29_16_fu_108_p1 & tmp_13_fu_168_p3);

assign and_ln374_12_fu_214_p2 = (trunc_ln29_15_fu_104_p1 & tmp_14_fu_206_p3);

assign and_ln374_13_fu_252_p2 = (trunc_ln29_14_fu_100_p1 & tmp_15_fu_244_p3);

assign and_ln374_14_fu_290_p2 = (trunc_ln29_13_fu_96_p1 & tmp_16_fu_282_p3);

assign and_ln374_15_fu_328_p2 = (trunc_ln29_12_fu_92_p1 & tmp_17_fu_320_p3);

assign and_ln374_16_fu_366_p2 = (trunc_ln29_11_fu_88_p1 & tmp_18_fu_358_p3);

assign and_ln374_17_fu_404_p2 = (trunc_ln29_fu_84_p1 & tmp_19_fu_396_p3);

assign and_ln374_fu_138_p2 = (trunc_ln29_17_fu_112_p1 & tmp_fu_130_p3);

assign ap_ready = 1'b1;

assign p_Val2_11_fu_154_p4 = {{p_read2[15:1]}};

assign p_Val2_12_fu_192_p4 = {{p_read3[15:1]}};

assign p_Val2_13_fu_230_p4 = {{p_read4[15:1]}};

assign p_Val2_14_fu_268_p4 = {{p_read5[15:1]}};

assign p_Val2_15_fu_306_p4 = {{p_read6[15:1]}};

assign p_Val2_16_fu_344_p4 = {{p_read8[15:1]}};

assign p_Val2_17_fu_382_p4 = {{p_read9[15:1]}};

assign p_Val2_s_fu_116_p4 = {{p_read1[15:1]}};

assign sext_ln818_11_fu_164_p1 = $signed(p_Val2_11_fu_154_p4);

assign sext_ln818_12_fu_202_p1 = $signed(p_Val2_12_fu_192_p4);

assign sext_ln818_13_fu_240_p1 = $signed(p_Val2_13_fu_230_p4);

assign sext_ln818_14_fu_278_p1 = $signed(p_Val2_14_fu_268_p4);

assign sext_ln818_15_fu_316_p1 = $signed(p_Val2_15_fu_306_p4);

assign sext_ln818_16_fu_354_p1 = $signed(p_Val2_16_fu_344_p4);

assign sext_ln818_17_fu_392_p1 = $signed(p_Val2_17_fu_382_p4);

assign sext_ln818_fu_126_p1 = $signed(p_Val2_s_fu_116_p4);

assign tmp_13_fu_168_p3 = p_read2[32'd1];

assign tmp_14_fu_206_p3 = p_read3[32'd1];

assign tmp_15_fu_244_p3 = p_read4[32'd1];

assign tmp_16_fu_282_p3 = p_read5[32'd1];

assign tmp_17_fu_320_p3 = p_read6[32'd1];

assign tmp_18_fu_358_p3 = p_read8[32'd1];

assign tmp_19_fu_396_p3 = p_read9[32'd1];

assign tmp_fu_130_p3 = p_read1[32'd1];

assign trunc_ln29_11_fu_88_p1 = p_read8[0:0];

assign trunc_ln29_12_fu_92_p1 = p_read6[0:0];

assign trunc_ln29_13_fu_96_p1 = p_read5[0:0];

assign trunc_ln29_14_fu_100_p1 = p_read4[0:0];

assign trunc_ln29_15_fu_104_p1 = p_read3[0:0];

assign trunc_ln29_16_fu_108_p1 = p_read2[0:0];

assign trunc_ln29_17_fu_112_p1 = p_read1[0:0];

assign trunc_ln29_fu_84_p1 = p_read9[0:0];

assign zext_ln377_11_fu_182_p1 = and_ln374_11_fu_176_p2;

assign zext_ln377_12_fu_220_p1 = and_ln374_12_fu_214_p2;

assign zext_ln377_13_fu_258_p1 = and_ln374_13_fu_252_p2;

assign zext_ln377_14_fu_296_p1 = and_ln374_14_fu_290_p2;

assign zext_ln377_15_fu_334_p1 = and_ln374_15_fu_328_p2;

assign zext_ln377_16_fu_372_p1 = and_ln374_16_fu_366_p2;

assign zext_ln377_17_fu_410_p1 = and_ln374_17_fu_404_p2;

assign zext_ln377_fu_144_p1 = and_ln374_fu_138_p2;

assign ap_return_0 = add_ln377_fu_148_p2;

assign ap_return_1 = add_ln377_11_fu_186_p2;

assign ap_return_2 = add_ln377_12_fu_224_p2;

assign ap_return_3 = add_ln377_13_fu_262_p2;

assign ap_return_4 = add_ln377_14_fu_300_p2;

assign ap_return_5 = add_ln377_15_fu_338_p2;

assign ap_return_6 = add_ln377_16_fu_376_p2;

assign ap_return_7 = add_ln377_17_fu_414_p2;

endmodule //inference_linear_ap_fixed_16_6_5_3_0_ap_fixed_16_7_4_0_0_linear_config10_s
